"""make collection optional for documents

Revision ID: 0eab9643020b
Revises: 31e29cc30d47
Create Date: 2026-07-26 23:29:37.297088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eab9643020b'
down_revision: Union[str, Sequence[str], None] = '31e29cc30d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'collection_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'collection_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
